#ifndef CONSTANTS_H
#define CONSTANTS_H

#define MAX_MODEL_LOCAL_COUNT 256
#define MAX_MODEL_WORLD_COUNT 16
#define MAX_POINT_LIGHT_COUNT 4
#define MAX_SPOT_LIGHT_COUNT 16
#define MAX_DIRECTIONAL_LIGHT_COUNT 1

#define ISM_SPLAT_THREADS_X 1024
#define ISM_PULLPUSH_THREADS_X 32
#define ISM_PULLPUSH_THREADS_Y 32
#define ISM_RANKING_THREADS_X 32
#define ISM_RANKING_THREADS_Y 32

#define SHADOW_TYPE_SM 0
#define SHADOW_TYPE_ISM 1
#define SHADOW_TYPE_ISM_LOW 2

#endif